### ISSUE TITLE
Unable to replace file

### ISSUE THREAD

**Issue by nathanaelmartel** [rande/swCombinePlugin#10]
Salut Thomas, 

J'ai l'erreur suivante :

Unable to replace file "(...)web/sw-combine/frontend/aa9b219f67624074aa6ae611eb06bda0.js" with optimized contents

Voici ce que donne un ls -la :
# ls -la web/sw-combine/frontend/

total 128
drwxr-xr-x 2 restaurant-levasion restaurant-levasion  4096 2011-03-15 11:53 .
drwxr-xr-x 3 restaurant-levasion restaurant-levasion  4096 2011-03-15 11:52 ..
-rw-r--r-- 1 root                root                29499 2011-03-15 11:53 12484cee2a614e047c4c9ea7cbc4f95c.css
-rw-r--r-- 1 root                root                23301 2011-03-15 11:53 1f034bb723f35c9164cf653ca7764d41.js
-rw-r--r-- 1 root                root                24138 2011-03-15 11:53 459cb1dc4fa76b8c3948dfa4933b8890.css
-rw-r--r-- 1 root                root                    0 2011-03-15 11:53 aa9b219f67624074aa6ae611eb06bda0.js
-rw-r--r-- 1 root                root                39589 2011-03-15 11:53 aa9b219f67624074aa6ae611eb06bda0.js.tmp

**Comment by rande** [comment]
it seems to be a permission issues : root vs restaurant-levasion

**Comment by nathanaelmartel** [comment]
well, 

sauf que je fais juste la commande ./symfony sw:combine (en root) qui supprime tout, qui génère le premier fichier et qui, quelque seconde plus tard n'arrive plus à y accéder...

J'ai essayé de faire :
chmod -R 777 web/sw-combine 
chown -R restaurant-lauthentique:restaurant-lauthentique web/sw-combine

et relancé derrière : même résultat.

**Comment by nathanaelmartel** [comment]
ok, désolé, il y avait un message d'erreur à la ligne au dessus : 
"Parse error: Missing ; before statement in file '[inline]' on line 8"
