### ISSUE TITLE
YUI Compressor

### ISSUE THREAD

**Issue by digitarald** [rande/swCombinePlugin#3]
Seriously, no YUI compressor?

Must have, should be in drivers by default. I will attach it here when I finished it.

**Comment by rande** [comment]
waiting for your patch ;)

**Comment by digitarald** [comment]
forking … one sec ;)

**Comment by digitarald** [comment]
http://github.com/rande/swCombinePlugin/pull/5

**Comment by rande** [comment]
thanks, your commit has been merged
